export const DatabaseEnvEnum = {
  DATABASE_URL: 'DATABASE_URL',
  DATABASE_NAME: 'DATABASE_NAME',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
} as const;
