export const LangfuseEnvEnum = {
  LANGFUSE_ENABLED: 'LANGFUSE_ENABLED',
  LANGFUSE_PUBLIC_KEY: 'LANGFUSE_PUBLIC_KEY',
  LANGFUSE_SECRET_KEY: 'LANGFUSE_SECRET_KEY',
  LANGFUSE_BASE_URL: 'LANGFUSE_BASE_URL',
  LANGFUSE_TRACING_ENVIRONMENT: 'LANGFUSE_TRACING_ENVIRONMENT',
  LANGFUSE_RELEASE: 'LANGFUSE_RELEASE',
  LANGFUSE_EXPORT_MODE: 'LANGFUSE_EXPORT_MODE',
} as const;
