export const MinioEnvEnum = {
  MINIO_END_POINT: 'MINIO_END_POINT',
  MINIO_PORT: 'MINIO_PORT',
  MINIO_ACCESS_KEY: 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY: 'MINIO_SECRET_KEY',
  MINIO_USE_SSL: 'MINIO_USE_SSL',
  MINIO_BUCKET: 'MINIO_BUCKET',
} as const;
